package otros;

public interface IConstants {

    //GUI constants
    int PANTALLA_ANCHURA = 350;
	int PANTALLA_ALTURA = 450;
	int PANTALLA_JUEGO_ANCHURA = 1024;
	int PANTALLA_JUEGO_ALTURA = 800;
	int DEFAULT_BUTTON_ANCHURA = 126;
	int DEFAULT_BUTTON_ALTURA = 30;
	int TEXTLABEL_ANCHURA = (PANTALLA_ANCHURA*80)/100;
    int DEFAUL_LABEL_WIDTH = 100;
    int DEFAUL_LABEL_HEIGHT = 20;

    int DEFAULT_BOTTON_X = (PANTALLA_ANCHURA / 2) - (DEFAULT_BUTTON_ANCHURA / 2);

    int USER_INPUT_X = PANTALLA_ANCHURA / 12;
    int PASSWORD_INPUT_X = PANTALLA_ANCHURA / 12;
    int USER_INPUT_Y = PANTALLA_ALTURA / 9;
    int PASSWORD_INPUT_Y = USER_INPUT_Y + DEFAULT_BUTTON_ALTURA + 30;
    int USER_LABEL_X = USER_INPUT_X;
    int USER_LABEL_Y = USER_INPUT_Y - 20;
    int PASSWORD_LABEL_X = PASSWORD_INPUT_X;
    int PASSWORD_LABEL_Y = PASSWORD_INPUT_Y - 20;
    int LOGIN_BOTTON_X = DEFAULT_BOTTON_X;
    int LOGIN_BOTTON_Y = PASSWORD_INPUT_Y + 40;
    int REGISTER_BOTTON_X = DEFAULT_BOTTON_X;
    int REGISTER_BOTTON_Y = LOGIN_BOTTON_Y + DEFAULT_BUTTON_ALTURA + 10;


    //Graph constants
	int CANTIDAD_NODOS_ANCHURA = 20;
	int CANTIDAD_NODOS_ALTURA = 13;
	int ALTURA_CASILLA =  PANTALLA_JUEGO_ALTURA / CANTIDAD_NODOS_ALTURA;
	int ANCHO_CASILLA = PANTALLA_JUEGO_ANCHURA / CANTIDAD_NODOS_ANCHURA;
	int FILA_CENTRAL = ( CANTIDAD_NODOS_ALTURA / 2 );
	int ULTIMA_FILA = CANTIDAD_NODOS_ALTURA - 1;
	int ULTIMA_COLUMNA = CANTIDAD_NODOS_ANCHURA - 1;
	int AREA_CASILLA = ALTURA_CASILLA * ANCHO_CASILLA;


	int CANT_HILOS = 5;
}
